kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gradle-cache
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
